### PR TITLE
Add Ubuntu Groovy (20.10)

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
Created the new Dockerfile to build Ubuntu Groovy based on Ubuntu Focal.

Was used next command:
`v.ioffe@v-ioffe tarantool.bcp % OS=ubuntu DIST=groovy ./packpack/packpack | tee log`

```
Result: 
------------------------------------------------------------------
Debian packages are ready
-------------------------------------------------------------------
   32 /source/build/tarantool-common_2.9.0.10.g7fd53b4c5-1_all.deb
  132 /source/build/tarantool-dev_2.9.0.10.g7fd53b4c5-1_amd64.deb
   16 /source/build/tarantool_2.9.0.10.g7fd53b4c5-1.debian.tar.xz
    4 /source/build/tarantool_2.9.0.10.g7fd53b4c5-1.dsc
 3076 /source/build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.build
    4 /source/build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.changes
10244 /source/build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.deb
    0 /source/build/tarantool_2.9.0.10.g7fd53b4c5.orig.tar.xz
--

make: Leaving directory '/source'
root@docker-desktop:/source# sudo apt install ./build/*.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
<....>
root@docker-desktop:/source# /usr/bin/tarantool
Tarantool 2.9.0-10-g7fd53b4c5
type 'help' for interactive help
tarantool> 
tarantool> box.cfg{}
2021-06-01 08:47:00.730 [16868] main/103/interactive C> Tarantool 2.9.0-10-g7fd53b4c5
2021-06-01 08:47:00.730 [16868] main/103/interactive C> log level 5
2021-06-01 08:47:00.730 [16868] main/103/interactive I> wal/engine cleanup is paused
2021-06-01 08:47:00.731 [16868] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2021-06-01 08:47:00.731 [16868] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-06-01 08:47:00.731 [16868] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2021-06-01 08:47:00.733 [16868] main/103/interactive I> instance uuid b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-01 08:47:00.734 [16868] main/103/interactive I> initializing an empty data directory
2021-06-01 08:47:00.757 [16868] main/103/interactive I> assigned id 1 to replica b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-01 08:47:00.757 [16868] main/103/interactive I> cluster uuid d7a8c1a4-7ca7-4291-bb10-b0178e278221
2021-06-01 08:47:00.769 [16868] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2021-06-01 08:47:00.772 [16868] snapshot/101/main I> done
2021-06-01 08:47:00.776 [16868] main/103/interactive I> ready to accept requests
2021-06-01 08:47:00.776 [16868] main/104/gc I> wal/engine cleanup is resumed
2021-06-01 08:47:00.777 [16868] main/103/interactive I> set 'log_level' configuration option to 5
2021-06-01 08:47:00.777 [16868] main/105/checkpoint_daemon I> scheduled next checkpoint for Tue Jun  1 10:14:59 2021
2021-06-01 08:47:00.778 [16868] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

<......>



tarantool> box.space.test:insert{1}
---
- [1]

root@docker-desktop:/source# grep ID /etc/os-release 
ID=ubuntu
ID_LIKE=debian
VERSION_ID="20.10"

```

Part of tarantool/tarantool#5824

### CODE REVIEW

**Comment by Totktonada** [comment]
Please, share results of testing. It would save some time for me: otherwise I'll need to repeat your steps.

My usual flow:

* Build an image, tag it as usual (`packpack/packpack:${OS}-${DIST}`).
* Temporary comment `docker pull <...>` in packpack.
* Run `OS=<...> DIST=<...> /path/to/packpack` in tarantool's repository root.

The result should be zero exit code and built packages in the `build/` directory.

Verify the built package using the base image (`ubuntu:groovy`, not `packpack/packpack:ubuntu-groovy`):

* Run a container.
* Install the package (and its dependencies).
* Smoke test for tarantool: run interactive console and execute some simple command.

----

BTW, please, reflect that you added two distros in the PR title and description. Use full link to the issue, because the short form (`#xxxx`) works only within a repository.

**Comment by VitaliyaIoffe** [comment]
```
v.ioffe@v-ioffe tarantool %docker run --network=host -w /source -v $PWD:/source -ti ubuntu:groovy /bin/bash
`root@docker-desktop:/source# dpkg -i ./build/*deb
<...>
dpkg: dependency problems prevent configuration of tarantool-common:
 tarantool-common depends on openssl; however:
  Package openssl is not installed.

dpkg: error processing package tarantool-common (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of tarantool:
 tarantool depends on libgomp1 (>= 4.9); however:
  Package libgomp1 is not installed.
 tarantool depends on libicu67 (>= 67.1-1~); however:
  Package libicu67 is not installed.
 tarantool depends on libreadline8 (>= 6.0); however:
  Package libreadline8 is not installed.
 tarantool depends on libunwind8; however:
  Package libunwind8 is not installed.
 tarantool depends on netbase; however:
  Package netbase is not installed.
 tarantool depends on binutils; however:
  Package binutils is not installed.
 tarantool depends on openssl; however:
  Package openssl is not installed.
 tarantool depends on tarantool-common (>= 1.7.5.46); however:
  Package tarantool-common is not configured yet.

dpkg: error processing package tarantool (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of tarantool-dev:
 tarantool-dev depends on tarantool (= 2.9.0.10.g7fd53b4c5-1); however:
  Package tarantool is not configured yet.

dpkg: error processing package tarantool-dev (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 tarantool-common
 tarantool
 tarantool-dev

root@docker-desktop:/source# apt-get update && apt-get install -y --force-yes \
>     sudo \
>     git \
>     build-essential \
>     cmake \
>     gdb \
>     ccache \
>     devscripts \
>     debhelper \
>     cdbs \
>     fakeroot \
>     lintian \
>     equivs \
>     rpm \
>     alien \
>     dh-systemd

root@docker-desktop:/source# /usr/bin/tarantool
Tarantool 2.9.0-10-g7fd53b4c5
type 'help' for interactive help
tarantool> box.cfg{}
2021-06-02 15:34:54.311 [428] main/103/interactive C> Tarantool 2.9.0-10-g7fd53b4c5
2021-06-02 15:34:54.312 [428] main/103/interactive C> log level 5
2021-06-02 15:34:54.312 [428] main/103/interactive I> wal/engine cleanup is paused
2021-06-02 15:34:54.325 [428] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2021-06-02 15:34:54.325 [428] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-06-02 15:34:54.325 [428] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2021-06-02 15:34:54.327 [428] main/103/interactive I> instance uuid b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-02 15:34:54.347 [428] main/103/interactive I> instance vclock {1: 22}
2021-06-02 15:34:54.350 [428] main/103/interactive I> recovery start
2021-06-02 15:34:54.350 [428] main/103/interactive I> recovering from `./00000000000000000000.snap'
2021-06-02 15:34:54.352 [428] main/103/interactive I> cluster uuid d7a8c1a4-7ca7-4291-bb10-b0178e278221
2021-06-02 15:34:54.357 [428] main/103/interactive I> assigned id 1 to replica b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-02 15:34:54.359 [428] main/103/interactive I> recover from `./00000000000000000000.xlog'
2021-06-02 15:34:54.359 [428] main/103/interactive I> done `./00000000000000000000.xlog'
2021-06-02 15:34:54.360 [428] main/103/interactive I> recover from `./00000000000000000016.xlog'
2021-06-02 15:34:54.360 [428] main/103/interactive I> done `./00000000000000000016.xlog'
2021-06-02 15:34:54.362 [428] main/103/interactive I> recover from `./00000000000000000022.xlog'
2021-06-02 15:34:54.362 [428] main/103/interactive I> done `./00000000000000000022.xlog'
2021-06-02 15:34:54.367 [428] main/103/interactive I> ready to accept requests
2021-06-02 15:34:54.367 [428] main/103/interactive C> leaving orphan mode
2021-06-02 15:34:54.368 [428] main/104/gc I> wal/engine cleanup is resumed
2021-06-02 15:34:54.368 [428] main/103/interactive I> set 'log_level' configuration option to 5
2021-06-02 15:34:54.368 [428] main/105/checkpoint_daemon I> scheduled next checkpoint for Wed Jun  2 16:50:20 2021
2021-06-02 15:34:54.368 [428] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

tarantool> 
`
```

**Review by Totktonada — APPROVED** [review]
LGTM.

**Comment by Totktonada** [comment]
Pushed to Docker Hub:

```
$ docker build -t packpack/packpack:ubuntu-groovy . && docker push packpack/packpack:ubuntu-groovy
<...>
ubuntu-groovy: digest: sha256:4d0e06bc88111ebec65beb361ccab9c199b9e8218bd60f6c624b5a9434e27e8e size: 1782
```

**Pull request merged**
