### PR TITLE
Add Ubuntu Focal (x86_64)

### PR DESCRIPTION
**Pull request by akopytov**

### CODE REVIEW

**Comment by Totktonada** [comment]
Fixes https://github.com/packpack/packpack/issues/120

**Comment by Totktonada** [comment]
Alexander (@avtikhon) agreed to verify the image against tarantool in the scope of https://github.com/tarantool/tarantool/issues/4863

**Comment by avtikhon** [comment]
Checked the patch and found that depends library libunwind8 is additionally needed:
```
diff --git a/ubuntu/focal/Dockerfile b/ubuntu/focal/Dockerfile
index 830688b..423af6f 100644
--- a/ubuntu/focal/Dockerfile
+++ b/ubuntu/focal/Dockerfile
@@ -35,7 +35,8 @@ RUN apt-get update && apt-get install -y --force-yes \
     equivs \
     rpm \
     alien \
-    dh-systemd
+    dh-systemd \
+    libunwind8
 
 # Enable sudo without password
 RUN echo '%adm ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
```
I've failed to update the patch because of permissions.
LGTM after this addition.

**Comment by Totktonada** [comment]
@avtikhon Why don't keep it in tarantool dependencies? It is not so general purpose to include here, IMHO.

**Comment by avtikhon** [comment]
> @avtikhon Why don't keep it in tarantool dependencies? It is not so general purpose to include here, IMHO.

Right, using apt installer all dependencies installed automatically, so my previous addition is not needed, please proceed with commit of the patch into trunk.

**Comment by Totktonada** [comment]
@akopytov @avtikhon Thanks!

**Pull request merged**
