### PR TITLE
Fix HTTP 404 in Ubuntu Xenial (aarch64) build.

### PR DESCRIPTION
**Pull request by akopytov**
The problem was in invalid URLs for xenial-security in
/etc/apt/sources.list.

### CODE REVIEW

**Comment by rtsisyk** [comment]
Hi, I don't see any problems with Xenial on aarch64:

```
$ docker run -t -i packpack/packpack:ubuntu-xenial-aarch64
root@2040bc78eee8:/# apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [102 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [102 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main Sources [302 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports xenial-updates/restricted Sources [3202 B]
Get:6 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe Sources [184 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 Packages [574 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe arm64 Packages [521 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports xenial-security/main Sources [82.1 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports xenial-security/restricted Sources [2779 B]
Get:11 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe Sources [29.6 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports xenial-security/main arm64 Packages [249 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe arm64 Packages [130 kB]
Fetched 2283 kB in 1s (1220 kB/s)                          
Reading package lists... Done
```

**Comment by akopytov** [comment]
Weird indeed, you appear to have correct URL's in sources.list (ports.ubuntu.com instead of security.ubuntu.com).

Anyway, that is on an already built packpack image. Can you actually try to build an AArch64 image using Dockerfile provided by the `aarch64` branch? I suspect the base aarch64/ubuntu:xenial image has been changed and now contains invalid URLs. So this PR is basically a workaround.

**Comment by rtsisyk** [comment]
> Can you actually try to build an AArch64 image using Dockerfile provided by the aarch64 branch? 

OK, let me try. I'll push this workaround if it works and we should probably notify upstream Ubuntu maintainers about this bug.

**Comment by rtsisyk** [comment]
I don't see any problems on Ubuntu Xenial on aarch64:

```
 ---> Running in 57f4c72b6ffb
 ---> 8d6751eb72c4
Removing intermediate container 57f4c72b6ffb
Successfully built 8d6751eb72c4
roman@aarch64:~/packpack-docker-images/ubuntu/xenial$ 
```

**Review by rtsisyk — COMMENTED** [review]
I can't reproduce this problem on the latest aarch64 branch.

**Comment by akopytov** [comment]
This is interesting. I'll keep looking into it, but here's the full log from my machine. This is from a clean https://github.com/packpack/packpack-docker-images clone:

```
$ make ubuntu-xenial
docker build -t packpack/packpack:ubuntu-xenial-aarch64 ubuntu/xenial/
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM aarch64/ubuntu:xenial
 ---> d72d6ee9a3c5
Step 2 : MAINTAINER Roman Tsisyk <roman@tarantool.org>
 ---> Using cache
 ---> b568176483f0
Step 3 : ENV LC_ALL "C.UTF-8" LANG "C.UTF-8"
 ---> Using cache
 ---> ee7f408f0933
Step 4 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 2bb2b003ca86
Step 5 : RUN echo 'apt::install-recommends "false";' > /etc/apt/apt.conf.d/00recommends
 ---> Using cache
 ---> 50bb3c0b4fd6
Step 6 : RUN apt-get update && apt-get install -y --force-yes     apt-transport-https     curl     wget     gnupg     ca-certificates     software-properties-common python-software-properties
 ---> Running in 2531bccd9a87
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial InRelease [247 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [29.6 kB]
Ign:5 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
Ign:6 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
Get:7 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease [102 kB]
Ign:5 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
Get:8 http://ports.ubuntu.com/ubuntu-ports xenial/universe Sources [9802 kB]
Ign:6 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
Ign:5 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
Ign:6 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
Err:5 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
  404  Not Found [IP: 91.189.88.162 80]
Ign:6 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
Get:9 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 Packages [1466 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports xenial/universe arm64 Packages [9493 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports xenial/multiverse arm64 Packages [146 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe Sources [184 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 Packages [574 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe arm64 Packages [521 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports xenial-updates/multiverse arm64 Packages [4024 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports xenial-backports/main arm64 Packages [4922 B]
Get:17 http://ports.ubuntu.com/ubuntu-ports xenial-backports/universe arm64 Packages [1648 B]
Fetched 22.8 MB in 2min 1s (187 kB/s)
Reading package lists...
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-arm64/Packages  404  Not Found [IP: 91.189.88.162 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y --force-yes     apt-transport-https     curl     wget     gnupg     ca-certificates     software-properties-common python-software-properties' returned a non-zero code: 100
Makefile:26: recipe for target 'ubuntu-xenial' failed
make: *** [ubuntu-xenial] Error 100
```

**Comment by rtsisyk** [comment]
I don't see security.ubuntu.com in the stock aarch64/ubuntu:xenial image:

```
$ docker run -t -i aarch64/ubuntu:xenial /bin/bash

# cat /etc/apt/sources.list|grep security
## review or updates from the Ubuntu security team.
## security team.
## or updates from the Ubuntu security team.
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted
# deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security universe
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse
# deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse

# apt-get update
Get:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease [247 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [102 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease [102 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [102 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports xenial/universe Sources [9802 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 Packages [1466 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports xenial/universe arm64 Packages [9493 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports xenial/multiverse arm64 Packages [146 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe Sources [184 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 Packages [574 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe arm64 Packages [521 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports xenial-updates/multiverse arm64 Packages [4024 B]
Get:13 http://ports.ubuntu.com/ubuntu-ports xenial-backports/main arm64 Packages [4922 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports xenial-backports/universe arm64 Packages [1648 B]
Get:15 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe Sources [29.6 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports xenial-security/main arm64 Packages [249 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe arm64 Packages [130 kB]
Fetched 23.2 MB in 9s (2474 kB/s)                                                                                                                 
Reading package lists... Done
```

Try to `docker pull aarch64/ubuntu:xenial`.

**Comment by akopytov** [comment]
Thanks, `docker pull aarch64/ubuntu:xenial` did the trick. Apparently they fixed it upstream over the last few days. Closing the PR.

**Pull request closed without merging**
