### PR TITLE
Add Debian 11/12 buulseye/bookworm images for aarch64

### PR DESCRIPTION
**Pull request by amdei**
Debian 12, code named Bookworm, will be released on June 10th 2023.
It's about time to prepare for their arrival.

Debian 11, is there for many years. How could we miss it existence for arm64?

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
Isn't this bullseye arm64? The existing files are multi arch.
https://hub.docker.com/layers/packpack/packpack/debian-bullseye/images/sha256-5ca6212c59eac307e639a1f3411bcd6df9519e0305be5b42ba757b17d660f2c8?context=explore

I think your other pull is all that is needed, and ubuntu:lunar.

It could be useful to use stable and testing as these would automatically follow releases.

**Comment by amdei** [comment]
Indeed...

On native ARM64 with tarantool 2.11.0 command
`ARCH=arm64 OS=debian DIST=bullseye make -f .pack.mk package`
shows
```
...
VERSION=2.11.0
+ docker pull packpack/packpack:debian-bullseye-aarch64
debian-bullseye-aarch64: Pulling from packpack/packpack
Digest: sha256:5ca6212c59eac307e639a1f3411bcd6df9519e0305be5b42ba757b17d660f2c8
Status: Image is up to date for packpack/packpack:debian-bullseye-aarch64
docker.io/packpack/packpack:debian-bullseye-aarch64
...
```

Seems I indeed missed something...
Are any of branches  other than master in this repo now obsolete?

**Comment by Totktonada** [comment]
We started to create multiarch images some time ago (it is just convenient).

Sorry, it is not very obvious from the repository itself. I should write some short guide.

All the new images are multiarch and resides on `master`. We're building them for amd64 and aarch64.

**Comment by amdei** [comment]
Closing this RP as the other one (https://github.com/packpack/packpack-docker-images/pull/97) does the same.

**Comment by amdei** [comment]
Closing

**Pull request closed without merging**
