### PR TITLE
ppc64le support with travis

### PR DESCRIPTION
**Pull request by grooverdan**
I don't intend you to merge this to master but I'll need you to create a ppc64le branch first and then either of us can change the base of the PR.

Includes travis for building and pushing the resulting images to dockerhub.

With DOCKER_USERNAME and DOCKER_PASSWORD set (in the travis UI) (and maybe DOCKER_REPO changed) will push on changes to this branch.

### CODE REVIEW

**Comment by grooverdan** [comment]
Any interest/feedback?

**Comment by akopytov** [comment]
I created the `ppc64le` branch based on `master`.

**Comment by akopytov** [comment]
Merged, but for Travis integration I need help on `DOCKER_USERNAME` and `DOCKER_PASSWORD` from @rtsisyk.

**Comment by grooverdan** [comment]
Thanks @akopytov

**Comment by grooverdan** [comment]
ping @rtsisyk, can we trigger this branch to add ppc64le images to dockerhub?

**Pull request merged**
