### PR TITLE
Add Fedora 35

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
Add Fedora 35 with multiarch support

Needs for: tarantool/tarantool#6692

### CODE REVIEW

**Comment by VitaliyaIoffe** [comment]
docker build for x86
```
v.ioffe@v-ioffe packpack-docker-images % docker build fedora/35 -t vitaliiaioffe/tarantool:fedora-35
[+] Building 242.0s (13/13) FINISHED                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                      0.2s
 => => transferring dockerfile: 938B                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/fedora:35                                                                                                              3.5s
 => [1/9] FROM docker.io/library/fedora:35@sha256:40ba585f0e25c096a08c30ab2f70ef3820b8ea5a4bdd16da0edbfc0a6952fa57                                                       15.0s
 => => resolve docker.io/library/fedora:35@sha256:40ba585f0e25c096a08c30ab2f70ef3820b8ea5a4bdd16da0edbfc0a6952fa57                                                        0.0s
 => => sha256:40ba585f0e25c096a08c30ab2f70ef3820b8ea5a4bdd16da0edbfc0a6952fa57 1.20kB / 1.20kB                                                                            0.0s
 => => sha256:762d7c5766839057fd9f96a0f2cedf143e2b818feb7767dc1bb70c00c4c3890a 529B / 529B                                                                                0.0s
 => => sha256:b78af7a836928efd44317e82c8f2f9c86bb83ae915deef1b58dc6465dfa5436e 2.00kB / 2.00kB                                                                            0.0s
 => => sha256:edad61c68e675e3c0fe2d02c0d21b9ca85334fcd8de115fc56764e72cb5bed6c 54.65MB / 54.65MB                                                                          6.5s
 => => extracting sha256:edad61c68e675e3c0fe2d02c0d21b9ca85334fcd8de115fc56764e72cb5bed6c                                                                                 7.3s
 => [2/9] RUN dnf update -v -y                                                                                                                                           64.6s
 => [3/9] RUN dnf -y group install 'Development Tools'                                                                                                                   88.4s
 => [4/9] RUN dnf -y group install 'C Development Tools and Libraries'                                                                                                   15.8s
 => [5/9] RUN dnf -y group install 'RPM Development Tools'                                                                                                               14.8s
 => [6/9] RUN dnf -y install fedora-packager                                                                                                                              8.8s
 => [7/9] RUN dnf -y install sudo git ccache cmake                                                                                                                        6.8s
 => [8/9] RUN sed -i.bak -n -e '/^Defaults.*requiretty/ { s/^/# /;};/^%wheel.*ALL$/ { s/^/# / ;} ;/^#.*wheel.*NOPASSWD/ { s/^#[ ]*//;};p' /etc/sudoers                    0.3s
 => [9/9] RUN dnf clean all                                                                                                                                               0.7s
 => exporting to image                                                                                                                                                   22.7s
 => => exporting layers                                                                                                                                                  22.7s
 => => writing image sha256:a71123b08ff546fb91128e29124b66ac900e0e606d7c036cd5e1b7a9baecda98                                                                              0.0s
 => => naming to docker.io/vitaliiaioffe/tarantool:fedora-35 
```

**Comment by VitaliyaIoffe** [comment]
docker build for arm64

```
v.ioffe@v-ioffe packpack-docker-images % docker build fedora/35 -t vitaliiaioffe/tarantool:fedora-35-arm64  --build-arg ARCH=arm64v8/
[+] Building 2819.9s (13/13) FINISHED                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                      0.0s
 => => transferring dockerfile: 37B                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/arm64v8/fedora:35                                                                                                              3.2s
 => [1/9] FROM docker.io/arm64v8/fedora:35@sha256:cfe295ee216d5995136f055659294ebc2dcbd736f94c5ac14dffb39fa2eebb27                                                       17.2s
 => => resolve docker.io/arm64v8/fedora:35@sha256:cfe295ee216d5995136f055659294ebc2dcbd736f94c5ac14dffb39fa2eebb27                                                        0.0s
 => => sha256:cfe295ee216d5995136f055659294ebc2dcbd736f94c5ac14dffb39fa2eebb27 529B / 529B                                                                                0.0s
 => => sha256:788739295edac7b7b34351db644c8a5506e7de56af398985c59bae8d87d45a1e 2.00kB / 2.00kB                                                                            0.0s
 => => sha256:3f28ea9d8c33c40fa95a05f63764cc6e8ef9d9449fd75da415eca42543b80f52 53.62MB / 53.62MB                                                                          6.6s
 => => extracting sha256:3f28ea9d8c33c40fa95a05f63764cc6e8ef9d9449fd75da415eca42543b80f52                                                                                 9.6s
 => [2/9] RUN dnf update -v -y                                                                                                                                         1499.7s
 => [3/9] RUN dnf -y group install 'Development Tools'                                                                                                                  646.6s
 => [4/9] RUN dnf -y group install 'C Development Tools and Libraries'                                                                                                  148.3s
 => [5/9] RUN dnf -y group install 'RPM Development Tools'                                                                                                              237.2s
 => [6/9] RUN dnf -y install fedora-packager                                                                                                                            128.6s
 => [7/9] RUN dnf -y install sudo git ccache cmake                                                                                                                      104.1s
 => [8/9] RUN sed -i.bak -n -e '/^Defaults.*requiretty/ { s/^/# /;};/^%wheel.*ALL$/ { s/^/# / ;} ;/^#.*wheel.*NOPASSWD/ { s/^#[ ]*//;};p' /etc/sudoers                    0.4s
 => [9/9] RUN dnf clean all                                                                                                                                              16.2s
 => exporting to image                                                                                                                                                   17.8s
 => => exporting layers                                                                                                                                                  17.8s
 => => writing image sha256:99d67c47e16395191f48721fe89904da0dc99401cadfcaff524b2f28e17d9537                                                                              0.0s
 => => naming to docker.io/vitaliiaioffe/tarantool:fedora-35-arm64
```

**Comment by artembo** [comment]
See workflow logs:
- fedora-35-amd64 https://github.com/tarantool/tarantool/runs/4878758089?check_suite_focus=true
- fedora-35-aarch64 https://github.com/tarantool/tarantool/runs/4878552519?check_suite_focus=true

**Comment by Totktonada** [comment]
Thanks!

**Pull request merged**
