### PR TITLE
Add multiarch approach to dockerfiles

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
Provide multiarch Dockerfiles for supported OS releases.

Needs for: tarantool/tarantool#6222

### CODE REVIEW

**Comment by VitaliyaIoffe** [comment]
`docker build packpack-docker-images/ubuntu/groovy -t packpack/packpack:ubuntu-groovy-aarch64 --build-arg ARCH=arm64v8/

docker build packpack-docker-images/ubuntu/groovy -t packpack/packpack:ubuntu-groovy-amd64

docker push  packpack/packpack:ubuntu-groovy-aarch64

docker push  packpack/packpack:ubuntu-groovy-amd64

docker manifest create packpack/packpack:ubuntu-groovy \
--amend packpack/packpack:ubuntu-groovy-aarch64 \
--amend packpack/packpack:ubuntu-groovy-amd64

 docker manifest push packpack/packpack:ubuntu-groovy
`

**Comment by Totktonada** [comment]
I have no objections in general. But I see that you updated some images and left some as is. What is the principle?

I want to see a list of images × architecture we're pushing to docker hub as master update. When we'll implement building / pushing from CI (https://github.com/packpack/packpack/issues/125), we'll move it to scripts. It is okay, if it'll contain only those images that you updated in the scope of your task: we'll expand the list later, actualize arch list, fix images with obsoleted repositories and so on.

**Comment by VitaliyaIoffe** [comment]
I left only that Dockerfiles, which would be used in the closed-closed future. 
Others we should check as part of packpack/packpack#139 issue.

**Comment by Totktonada** [comment]
@VitaliyaIoffe Please, update the images manually and list updated images there.

**Comment by VitaliyaIoffe** [comment]
### Fedora's images were published
**Fedora-33**
```
docker build --no-cache ./fedora/33 -t packpack/packpack:fedora-33-amd64 
docker build --no-cache ./fedora/33 -t packpack/packpack:fedora-33-aarch64 --build-arg ARCH=arm64v8/ 
        
docker push packpack/packpack:fedora-33-aarch64 &&
docker push packpack/packpack:fedora-33-amd64
fedora-33-aarch64: digest: sha256:1623051a1b3cd373c6ce9dc0e78785306b832975fd5c690ddea1ee5fdf1bb131 size: 2220
fedora-33-amd64: digest: sha256:f4e2e5793ead30e89154ea8088032e677de563f360c44c5886b0a73fb62204ed size: 2220

docker manifest create packpack/packpack:fedora-33 --amend packpack/packpack:fedora-33-aarch64 --amend packpack/packpack:fedora-33-amd64 &&
docker manifest push packpack/packpack:fedora-33

Created manifest list docker.io/packpack/packpack:fedora-33
sha256:642bb93ff77f0075d2acd9cf981a3c45e8503856d9fa7c2e90ede5c55489b541   
....
                
```
**Fedora-34**

```
docker build --no-cache ./fedora/34 -t packpack/packpack:fedora-34-aarch64 --build-arg ARCH=arm64v8/
docker build --no-cache ./fedora/34 -t packpack/packpack:fedora-34-amd64
 docker push packpack/packpack:fedora-34-aarch64 &&
docker push packpack/packpack:fedora-34-amd64
fedora-34-aarch64: digest: sha256:aa22c8b9c37186e0b24c4995d2908a2a0a7994c1d2daa8c64be13741202a6403 size: 2220
fedora-34-amd64: digest: sha256:236d77776fd077f244cfeaa017c8b66979cc40357bc17723c7a4cb3a1aa11c0b size: 2220
docker manifest create packpack/packpack:fedora-34 --amend packpack/packpack:fedora-34-aarch64 --amend packpack/packpack:fedora-34-amd64 &&
docker manifest push packpack/packpack:fedora-34

Created manifest list docker.io/packpack/packpack:fedora-34
sha256:d028f8e4cb8430fcf8bf3820a48cb89267228a2130fbe25bfafd2fc2b739e8b3


```

**CentOS-7**
```

docker push packpack/packpack:el-7-aarch64 &&
docker push packpack/packpack:el-7-amd64
el-7-aarch64: digest: sha256:9a1bc046131f06f83d00da44211a45501d2a7b791d485d372d677843cec918ca size: 3677

el-7-amd64: digest: sha256:808f1453e49f33699a1e5b4469354129d1ecdfa304d84514ac9c0926d4293e22 size: 3675
docker manifest create packpack/packpack:el-7 --amend packpack/packpack:el-7-aarch64 --amend packpack/packpack:el-7-amd64 &&
docker manifest push packpack/packpack:el-7
Created manifest list docker.io/packpack/packpack:el-7
sha256:8959d5477d2512448c11358efa65849a44dc7ded9a0f69399bd65231ca2e688a
```
**CentOS-8**
```docker push packpack/packpack:el-8-aarch64 &&
docker push packpack/packpack:el-8-amd64
el-8-aarch64: digest: sha256:da38f15a34b61cf2b26881a52633be1516ba05f0537926f4209636ec1cb3c59d size: 2637
2653d992f4ef: Layer already exists 
el-8-amd64: digest: sha256:244091471220bc30db0769157fa83beb940d98d1e27375a70bc4e77f8a0632e4 size: 2637
docker manifest create packpack/packpack:el-8 --amend packpack/packpack:el-8-aarch64 --amend packpack/packpack:el-8-amd64 &&
docker manifest push packpack/packpack:el-8
Created manifest list docker.io/packpack/packpack:el-8
sha256:aa23d8748466f2331d49ea36fe93e72063d370b1bc9956325ff7b56a3eec6a00

```

**Comment by VitaliyaIoffe** [comment]
### Ubuntu images were pushed
**Ubuntu-groovy**
```
docker build --no-cache ./ubuntu/groovy -t packpack/packpack:ubuntu-groovy-aarch64 --build-arg ARCH=arm64v8/
docker build --no-cache ./ubuntu/groovy -t packpack/packpack:ubuntu-groovy-amd64                            

docker push packpack/packpack:ubuntu-groovy-aarch64
ubuntu-groovy-aarch64: digest: sha256:cd48de5732d7c1b3b70a6b261784ab71e0d365a6fd1f3d2f0e3447030c285a31 size: 1368
docker push packpack/packpack:ubuntu-groovy-amd64
ubuntu-groovy-amd64: digest: sha256:9a1cfdcbbef0f5fe220de88d061a49563067dd0c26e943b7ed1621e79cc16d1b size: 1368

docker manifest create packpack/packpack:ubuntu-groovy --amend packpack/packpack:ubuntu-groovy-aarch64 --amend packpack/packpack:ubuntu-groovy-amd64
Created manifest list docker.io/packpack/packpack:ubuntu-groovy

docker manifest push packpack/packpack:ubuntu-groovy
sha256:efa9ade930b2ed2cb7eb55590fadf56db5273c675ab091d7f27f224f0d64a072
```

**Ubuntu-hirsute**
```
docker build --no-cache ./ubuntu/hirsute -t packpack/packpack:ubuntu-hirsute-amd64
docker push packpack/packpack:ubuntu-hirsute-amd64
ubuntu-hirsute-amd64: digest: sha256:3d1b9105597d6de5d19ebcfaf24a0759bfe34fcae45d7373eec2104ce2a72b5a size: 1368

docker build --no-cache ./ubuntu/hirsute -t packpack/packpack:ubuntu-hirsute-aarch64 --build-arg ARCH=arm64v8/
docker push packpack/packpack:ubuntu-hirsute-aarch64
ubuntu-hirsute-aarch64: digest: sha256:ced8d801611a22d90f7a000f56246a6d6af3d357ae649989159527a4a0379128 size: 1368

docker manifest create packpack/packpack:ubuntu-hirsute --amend packpack/packpack:ubuntu-hirsute-aarch64 --amend packpack/packpack:ubuntu-hirsute-amd64
docker manifest push packpack/packpack:ubuntu-hirsute
sha256:3147e6e751410e02a40d5a626457b2b76a811ae15beb5de593fdedd9fe101001

```
**Ubuntu-focal**
```
docker build --no-cache ./ubuntu/focal -t packpack/packpack:ubuntu-focal-amd64  
docker push packpack/packpack:ubuntu-focal-amd64    
ubuntu-focal-amd64: digest: sha256:49a2a7dab483ec45e62e8f7638aad93e3ecd183c53adb21f50d55bc26ff6eca9 size: 1368

docker build --no-cache ./ubuntu/focal -t packpack/packpack:ubuntu-focal-aarch64 --build-arg ARCH=arm64v8/
docker push packpack/packpack:ubuntu-focal-aarch64
ubuntu-focal-aarch64: digest: sha256:f905e43ef15533a25ad8e07faf3d3a648d982255688f2aa52d52615a286aedf9 size: 1368

docker manifest create packpack/packpack:ubuntu-focal --amend packpack/packpack:ubuntu-focal-aarch64 --amend packpack/packpack:ubuntu-focal-amd64
docker manifest push packpack/packpack:ubuntu-focal
sha256:34e899e2562ce9f0b3ea6cbd007270a23cf04316169e67e7c61543ac4f50c325

```

**Comment by VitaliyaIoffe** [comment]
### Debian images were published

**debian-buster**
```
docker build --no-cache ./debian/buster/ -t packpack/packpack:debian-buster-aarch64 --build-arg ARCH=arm64v8/  
docker build --no-cache ./debian/buster -t packpack/packpack:debian-buster-amd64 
docker push packpack/packpack:debian-buster-aarch64
debian-buster-aarch64: digest: sha256:030114f0ea5642a95721540525ef026e931d4c94fc09ed5916530ba023e86a2f size: 1368
docker push packpack/packpack:debian-buster-amd64
debian-buster-amd64: digest: sha256:7c2ed82870597bfa654a6372ff1ad3166bf597d1b6116c15b8cfd9e16375b482 size: 1368
docker manifest create packpack/packpack:debian-buster --amend packpack/packpack:debian-buster-aarch64 --amend packpack/packpack:debian-buster-amd64
Created manifest list docker.io/packpack/packpack:debian-buster
docker manifest push packpack/packpack:debian-buster
sha256:9c6af7b0a19b35082310640660a66c5c8dea0dd599a95b2073a33c1794cd5643

```
**debian-bullseye**
```
docker build --no-cache ./debian/bullseye -t packpack/packpack:debian-bullseye-amd64 
docker build --no-cache ./debian/bullseye -t packpack/packpack:debian-bullseye-aarch64 --build-arg ARCH=arm64v8/


docker push packpack/packpack:debian-bullseye-aarch64
debian-bullseye-aarch64: digest: sha256:5ca6212c59eac307e639a1f3411bcd6df9519e0305be5b42ba757b17d660f2c8 size: 1368
docker push packpack/packpack:debian-bullseye-amd64 
debian-bullseye-amd64: digest: sha256:ccd36a5d36c0286d3b1c647731d2ed7e7df97992be86a2b7b3c139d4c4282502 size: 1368
docker manifest push packpack/packpack:debian-bullseye
sha256:6df84393e592ffc329031c2fac6fcf3068aaa60ae08edf2406d446c522c93eb3

```

**Pull request merged**
