### PR TITLE
Add Fedora 31 (x86_64)

### PR DESCRIPTION
**Pull request by akopytov**

### CODE REVIEW

**Comment by Totktonada** [comment]
We need to enable backports repository: see fedora/27/Dockerfile (but remove pygpgme, it seems it was deprecated as well as in CentOS 8). Fedora 31 [drops](https://fedoraproject.org/wiki/Releases/31/ChangeSet#F31_Mass_Python_2_Package_Removal) some Python 2 packages like python2-gevent (formerly python-gevent). (Hope we’ll end with porting of test-run to Python 3 soon, but now we need [some](https://github.com/tarantool/test-run/blob/e665a66013dc1d2edf11f53a35fbdd1128b2274b/requirements.txt) Python 2 packages.)

packagecloud.io does not support fedora/31 for now, but I wrote a email to support: they are usually very responsible about such questions.

Small style nitpicking: headers are usually does not contain a period at the end: it is applicable for commit message headers too.

When everything will be resolved (from your side and packagecloud side), I’ll verify the image locally on tarantool. If everything will be ok, I’ll push the PR and the docker image to Docker Hub.

Thank you!

**Comment by akopytov** [comment]
I sent an email to packagecloud.io regarding Fedora 31 support on Oct 30. There's still no response.

**Comment by Totktonada** [comment]
packagecloud.io team enables fedora/31, but now we get an error at uploading a package for the distro. PackageCloud support said that they need 'at least a week or so to track down the issue'.

**Comment by Totktonada** [comment]
PackageCloud resolves the issue. Backports were uploaded https://travis-ci.org/packpack/packpack/builds/609497478

**Comment by akopytov** [comment]
@Totktonada I don't quite understand what needs to be done on my side. I don't use backports, and changes in this PR work just fine for me.

So if you are waiting on me, don't! :) If you need any further changes, feel free to either amend this PR, or replace it with a new one.

**Comment by Totktonada** [comment]
I'm currently waiting for Alexander (@avtikhon) to update the PR with backports enabling. After that we'll verify that the image will work good for building of tarantool and that will be a green light for the PR.

**Review by Totktonada — APPROVED** [review]
Everything looks okay.

**Pull request merged**
