### PR TITLE
Add Ubuntu Hirsute (21.04)

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
Created the new Dockerfile to build Ubuntu Hirsute based on Ubuntu Focal
Delete dh-systemd due to it was removed from this release.

Part of tarantool/tarantool#5825

### CODE REVIEW

**Comment by VitaliyaIoffe** [comment]
```
v.ioffe@v-ioffe tarantool % OS=ubuntu DIST=hirsute ./packpack/packpack | tee log
Part of #issue-810205776


Finished running lintian.
rm -rf /build/tarantool-2.9.0.10/
------------------------------------------------------------------
Debian packages are ready
-------------------------------------------------------------------
   32 /build/tarantool-common_2.9.0.10.g7fd53b4c5-1_all.deb
  132 /build/tarantool-dev_2.9.0.10.g7fd53b4c5-1_amd64.deb
   16 /build/tarantool_2.9.0.10.g7fd53b4c5-1.debian.tar.xz
    4 /build/tarantool_2.9.0.10.g7fd53b4c5-1.dsc
 3076 /build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.build
    4 /build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.changes
10244 /build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.deb
    0 /build/tarantool_2.9.0.10.g7fd53b4c5.orig.tar.xz
--

make: Leaving directory '/source'
+ retcode=0
+ rm -f /Users/v.ioffe/tarantool_bcp/build/userwrapper.sh /Users/v.ioffe/tarantool_bcp/build/env
+ exit 0
v.ioffe@v-ioffe tarantool % docker run --network=host -w /source -v $PWD:/source -ti packpack/packpack:ubuntu-hirsute /bin/bash
root@docker-desktop:/source# sudo apt install ./build/*.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'tarantool-common' instead of './build/tarantool-common_2.9.0.10.g7fd53b4c5-1_all.deb'
Note, selecting 'tarantool-dev' instead of './build/tarantool-dev_2.9.0.10.g7fd53b4c5-1_amd64.deb'
Note, selecting 'tarantool' instead of './build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.deb'
The following NEW packages will be installed:
  tarantool tarantool-common tarantool-dev
0 upgraded, 3 newly installed, 0 to remove and 5 not upgraded.
Need to get 0 B/9711 kB of archives.
After this operation, 42.1 MB of additional disk space will be used.
Get:1 /source/build/tarantool-common_2.9.0.10.g7fd53b4c5-1_all.deb tarantool-common all 2.9.0.10.g7fd53b4c5-1 [32.7 kB]
Get:2 /source/build/tarantool_2.9.0.10.g7fd53b4c5-1_amd64.deb tarantool amd64 2.9.0.10.g7fd53b4c5-1 [9599 kB]
Get:3 /source/build/tarantool-dev_2.9.0.10.g7fd53b4c5-1_amd64.deb tarantool-dev amd64 2.9.0.10.g7fd53b4c5-1 [79.3 kB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package tarantool-common.
(Reading database ... 27972 files and directories currently installed.)
Preparing to unpack .../tarantool-common_2.9.0.10.g7fd53b4c5-1_all.deb ...
Unpacking tarantool-common (2.9.0.10.g7fd53b4c5-1) ...
Selecting previously unselected package tarantool.
Preparing to unpack .../tarantool_2.9.0.10.g7fd53b4c5-1_amd64.deb ...
Unpacking tarantool (2.9.0.10.g7fd53b4c5-1) ...
Selecting previously unselected package tarantool-dev.
Preparing to unpack .../tarantool-dev_2.9.0.10.g7fd53b4c5-1_amd64.deb ...
Unpacking tarantool-dev (2.9.0.10.g7fd53b4c5-1) ...
Setting up tarantool-common (2.9.0.10.g7fd53b4c5-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/tarantool.service → /lib/systemd/system/tarantool.service.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up tarantool (2.9.0.10.g7fd53b4c5-1) ...
update-alternatives: using /usr/bin/tarantool to provide /usr/bin/lua (lua-interpreter) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lua.1.gz because associated file /usr/share/man/man1/tarantool.1.gz (of link group lua-interpreter) doesn't exist
Setting up tarantool-dev (2.9.0.10.g7fd53b4c5-1) ...
Processing triggers for man-db (2.9.4-2) ...
root@docker-desktop:/source# /usr/bin/tarantool
Tarantool 2.9.0-10-g7fd53b4c5
type 'help' for interactive help
tarantool> box.cfg{}
2021-06-01 14:24:11.569 [98] main/103/interactive C> Tarantool 2.9.0-10-g7fd53b4c5
2021-06-01 14:24:11.570 [98] main/103/interactive C> log level 5
2021-06-01 14:24:11.570 [98] main/103/interactive I> wal/engine cleanup is paused
2021-06-01 14:24:11.585 [98] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2021-06-01 14:24:11.585 [98] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-06-01 14:24:11.585 [98] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2021-06-01 14:24:11.588 [98] main/103/interactive I> instance uuid b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-01 14:24:11.605 [98] main/103/interactive I> instance vclock {1: 22}
2021-06-01 14:24:11.607 [98] main/103/interactive I> recovery start
2021-06-01 14:24:11.607 [98] main/103/interactive I> recovering from `./00000000000000000000.snap'
2021-06-01 14:24:11.611 [98] main/103/interactive I> cluster uuid d7a8c1a4-7ca7-4291-bb10-b0178e278221
2021-06-01 14:24:11.618 [98] main/103/interactive I> assigned id 1 to replica b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-01 14:24:11.620 [98] main/103/interactive I> recover from `./00000000000000000000.xlog'
2021-06-01 14:24:11.620 [98] main/103/interactive I> done `./00000000000000000000.xlog'
2021-06-01 14:24:11.621 [98] main/103/interactive I> recover from `./00000000000000000016.xlog'
2021-06-01 14:24:11.622 [98] main/103/interactive I> done `./00000000000000000016.xlog'
2021-06-01 14:24:11.623 [98] main/103/interactive I> recover from `./00000000000000000022.xlog'
2021-06-01 14:24:11.623 [98] main/103/interactive I> done `./00000000000000000022.xlog'
2021-06-01 14:24:11.630 [98] main/103/interactive I> ready to accept requests
2021-06-01 14:24:11.630 [98] main/103/interactive C> leaving orphan mode
2021-06-01 14:24:11.630 [98] main/104/gc I> wal/engine cleanup is resumed
2021-06-01 14:24:11.631 [98] main/103/interactive I> set 'log_level' configuration option to 5
2021-06-01 14:24:11.631 [98] main/105/checkpoint_daemon I> scheduled next checkpoint for Tue Jun  1 15:43:19 2021
2021-06-01 14:24:11.631 [98] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

tarantool> 
```

**Comment by VitaliyaIoffe** [comment]
```
v.ioffe@v-ioffe tarantool %docker run --network=host -w /source -v $PWD:/source -ti ubuntu:hirsute /bin/bash

root@docker-desktop:/source# apt-get update && apt-get install -y --force-yes     sudo     git     build-essential     cmake     gdb     ccache     devscripts     debhelper     cdbs     fakeroot     lintian     equivs     rpm     alien
<....>
W: --force-yes is deprecated, use one of the options starting with --allow instead.
root@docker-desktop:/source# dpkg -i ./build/*.deb
Selecting previously unselected package tarantool-common.
(Reading database ... 31071 files and directories currently installed.)
Preparing to unpack .../tarantool-common_2.9.0.10.g7fd53b4c5-1_all.deb ...
Unpacking tarantool-common (2.9.0.10.g7fd53b4c5-1) ...
Selecting previously unselected package tarantool-dev.
Preparing to unpack .../tarantool-dev_2.9.0.10.g7fd53b4c5-1_amd64.deb ...
Unpacking tarantool-dev (2.9.0.10.g7fd53b4c5-1) ...
Selecting previously unselected package tarantool.
Preparing to unpack .../tarantool_2.9.0.10.g7fd53b4c5-1_amd64.deb ...
Unpacking tarantool (2.9.0.10.g7fd53b4c5-1) ...
Setting up tarantool-common (2.9.0.10.g7fd53b4c5-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up tarantool (2.9.0.10.g7fd53b4c5-1) ...
update-alternatives: using /usr/bin/tarantool to provide /usr/bin/lua (lua-interpreter) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lua.1.gz because associated file /usr/share/man/man1/tarantool.1.gz (of link group lua-interpreter) doesn't exist
Setting up tarantool-dev (2.9.0.10.g7fd53b4c5-1) ...
Processing triggers for man-db (2.9.4-2) ...
root@docker-desktop:/source# /usr/bin/tar
tar           tarantool     tarantoolctl  
root@docker-desktop:/source# /usr/bin/tar
tar           tarantool     tarantoolctl  
root@docker-desktop:/source# /usr/bin/tarantool
Tarantool 2.9.0-10-g7fd53b4c5
type 'help' for interactive help
tarantool> box.cfg
---
- 'function: 0x41a3e6d8'
...

tarantool> box.cfg{}
2021-06-02 18:40:35.444 [7532] main/103/interactive C> Tarantool 2.9.0-10-g7fd53b4c5
2021-06-02 18:40:35.444 [7532] main/103/interactive C> log level 5
2021-06-02 18:40:35.444 [7532] main/103/interactive I> wal/engine cleanup is paused
2021-06-02 18:40:35.458 [7532] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2021-06-02 18:40:35.458 [7532] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-06-02 18:40:35.458 [7532] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2021-06-02 18:40:35.424 [7532] main/103/interactive I> instance uuid b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-02 18:40:35.441 [7532] main/103/interactive I> instance vclock {1: 22}
2021-06-02 18:40:35.443 [7532] main/103/interactive I> recovery start
2021-06-02 18:40:35.443 [7532] main/103/interactive I> recovering from `./00000000000000000000.snap'
2021-06-02 18:40:35.444 [7532] main/103/interactive I> cluster uuid d7a8c1a4-7ca7-4291-bb10-b0178e278221
2021-06-02 18:40:35.450 [7532] main/103/interactive I> assigned id 1 to replica b1629bf0-87e4-4354-94b6-a391436345a0
2021-06-02 18:40:35.452 [7532] main/103/interactive I> recover from `./00000000000000000000.xlog'
2021-06-02 18:40:35.452 [7532] main/103/interactive I> done `./00000000000000000000.xlog'
2021-06-02 18:40:35.453 [7532] main/103/interactive I> recover from `./00000000000000000016.xlog'
2021-06-02 18:40:35.453 [7532] main/103/interactive I> done `./00000000000000000016.xlog'
2021-06-02 18:40:35.455 [7532] main/103/interactive I> recover from `./00000000000000000022.xlog'
2021-06-02 18:40:35.455 [7532] main/103/interactive I> done `./00000000000000000022.xlog'
2021-06-02 18:40:35.461 [7532] main/103/interactive I> ready to accept requests
2021-06-02 18:40:35.461 [7532] main/103/interactive C> leaving orphan mode
2021-06-02 18:40:35.461 [7532] main/104/gc I> wal/engine cleanup is resumed
2021-06-02 18:40:35.461 [7532] main/103/interactive I> set 'log_level' configuration option to 5
2021-06-02 18:40:35.461 [7532] main/105/checkpoint_daemon I> scheduled next checkpoint for Wed Jun  2 20:11:53 2021
2021-06-02 18:40:35.462 [7532] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

tarantool> 
```

**Review by Totktonada — APPROVED** [review]
LGTM.

**Comment by Totktonada** [comment]
Pushed to Docker Hub:

```
$ docker build --no-cache -t packpack/packpack:ubuntu-hirsute . && docker push packpack/packpack:ubuntu-hirsute
<...>
ubuntu-hirsute: digest: sha256:49246186e726b588ade04b527c83d1f102306c79486a42d9737c34d5a08f9d16 size: 1782
```

**Pull request merged**
